# Generated by Django 2.2.1 on 2019-06-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(db_column='用户编号', primary_key=True, serialize=False)),
                ('user_name', models.EmailField(db_column='用户名', max_length=254, unique=True)),
                ('password', models.CharField(db_column='密码', max_length=128)),
                ('user_type', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], db_column='管理员', default=0)),
                ('user_tel', models.CharField(db_column='电话', default='9352', max_length=20)),
                ('user_createTime', models.DateField(auto_now_add=True, db_column='创建时间')),
                ('user_updateTime', models.DateField(auto_now=True, db_column='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token_id', models.AutoField(db_column='证书编号', primary_key=True, serialize=False)),
                ('token_code', models.CharField(db_column='证书', max_length=128)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yoyakumachine.UserInfo')),
            ],
        ),
    ]
